services:
  - type: web
    name: mountain-guide
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: python manage.py migrate --no-input && gunicorn summitguide.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: mountain-guide.onrender.com,guide.jadensingh.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://mountain-guide.onrender.com,https://guide.jadensingh.com
      - key: DATABASE_URL
        sync: false
