# Generated by Django 6.0.5 on 2026-05-27 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Peak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("state", models.CharField(default="Wyoming", max_length=80)),
                ("country", models.CharField(default="United States", max_length=80)),
                ("range_name", models.CharField(blank=True, max_length=160)),
                ("location", models.CharField(blank=True, max_length=220)),
                ("elevation_ft", models.PositiveIntegerField(blank=True, null=True)),
                ("prominence_ft", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("owner_notes", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=200)),
                ("yds_class", models.CharField(blank=True, max_length=40)),
                ("snow_grade", models.CharField(blank=True, max_length=80)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "peak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="mountains.peak",
                    ),
                ),
            ],
            options={
                "ordering": ["peak", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="RouteAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("attempted", "Attempted"),
                            ("climbed", "Climbed"),
                            ("turned_around", "Turned around"),
                        ],
                        max_length=24,
                    ),
                ),
                ("attempt_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "peak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_attempts",
                        to="mountains.peak",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="mountains.route",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-attempt_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SourceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("summitpost", "SummitPost"),
                            ("peakbagger", "Peakbagger"),
                            ("survey", "Survey source"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("url", models.URLField()),
                ("external_id", models.CharField(blank=True, max_length=120)),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("raw_snapshot", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "peak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="mountains.peak",
                    ),
                ),
            ],
            options={
                "ordering": ["source_type", "title"],
            },
        ),
        migrations.AddField(
            model_name="route",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="routes",
                to="mountains.sourcerecord",
            ),
        ),
        migrations.CreateModel(
            name="ContentSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("overview", "Overview"),
                            ("approach", "Approach"),
                            ("red_tape", "Red tape / permits"),
                            ("camping", "Camping"),
                            ("photos", "Photos"),
                            ("comments", "Comments"),
                            ("external_links", "External links"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("body", models.TextField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_imported", models.BooleanField(default=True)),
                ("visible_to_public", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "peak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_sections",
                        to="mountains.peak",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_sections",
                        to="mountains.sourcerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="TripReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("body", models.TextField()),
                ("trip_date", models.DateField(blank=True, null=True)),
                ("is_imported", models.BooleanField(default=False)),
                ("visible_to_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trip_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "peak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_reports",
                        to="mountains.peak",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trip_reports",
                        to="mountains.route",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trip_reports",
                        to="mountains.sourcerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-trip_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RouteRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(help_text="1-5")),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="mountains.route",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "route")},
            },
        ),
        migrations.CreateModel(
            name="SavedPeak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "peak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="mountains.peak",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_peaks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "peak")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="route",
            unique_together={("peak", "slug")},
        ),
    ]
