# Generated by Django 6.0.5 on 2026-05-27 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mountains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportedPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=600)),
                ("source_page_url", models.URLField(blank=True, max_length=600)),
                ("alt_text", models.CharField(blank=True, max_length=260)),
                ("caption", models.CharField(blank=True, max_length=500)),
                ("credit", models.CharField(blank=True, max_length=180)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_imported", models.BooleanField(default=True)),
                ("visible_to_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "peak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imported_photos",
                        to="mountains.peak",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="mountains.contentsection",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imported_photos",
                        to="mountains.sourcerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "unique_together": {("peak", "image_url")},
            },
        ),
    ]
